# Generated by Django 5.2 on 2025-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('motor', 'Motorika'), ('speech', 'Řeč'), ('social', 'Sociální vývoj')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills/')),
            ],
        ),
    ]
