# Generated by Django 5.2 on 2025-12-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
    ]
