# Generated by Django 5.2 on 2025-12-16 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_remove_skill_category_remove_skill_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('motor', 'Motorika'), ('speech', 'Řeč'), ('social', 'Sociální vývoj'), ('kognitivní', 'Kognitivní')], default='motor', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='Výchozí popis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='max_age_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skill',
            name='min_age_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Výchozí popis', max_length=200),
            preserve_default=False,
        ),
    ]
