# Generated by Django 5.2 on 2025-12-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_category_skill_description_skill_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('motor', 'Motorika'), ('speech', 'Řeč'), ('social', 'Sociální vývoj'), ('cognitive', 'Kognitivní')], default='motor', max_length=100),
        ),
    ]
