# Generated by Django 5.2 on 2025-12-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='max_age_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='min_age_date',
        ),
        migrations.AddField(
            model_name='skill',
            name='max_age_months',
            field=models.PositiveIntegerField(default=72),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='min_age_months',
            field=models.PositiveIntegerField(default=72),
            preserve_default=False,
        ),
    ]
