# Generated by Django 5.2 on 2025-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_remove_skill_max_age_date_remove_skill_min_age_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Имя иконки на фронте (без пути)', max_length=100),
        ),
    ]
