# Generated by Django 5.2 on 2025-12-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_remove_skill_image_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age_months', models.PositiveIntegerField()),
                ('max_age_months', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Název ikony na frontendu (bez cesty)', max_length=100),
        ),
    ]
